#!/bin/sh /etc/rc.common

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

CONFIG_DIR=/etc/shadowsocks
CONFIG_TCP=$CONFIG_DIR/tcp.json
CONFIG_UDP=$CONFIG_DIR/udp.json
CONFIG_DNS=$CONFIG_DIR/dns.json
CONFIG_IPFILE=$CONFIG_DIR/ip.txt
CONFIG_GFWLIST=$CONFIG_DIR/shadowsocks_gfwlist.conf
CONFIG_CUSLIST=$CONFIG_DIR/shadowsocks_custom.conf
LOCK_FILE=/var/run/shadowsocksvpn.lock

start() {

	if ! mkdir $LOCK_FILE 
	then
		echo "shadowsocks is already running, stop it first"
		exit 0
	fi

	service_start /usr/bin/ss-redir-tcp -c $CONFIG_TCP -b 0.0.0.0 -l 1081
	sleep 1
	service_start /usr/bin/ss-redir-udp -c $CONFIG_UDP -b 0.0.0.0 -l 1082 -U &
	sleep 1
	service_start /usr/bin/ss-tunnel -c $CONFIG_DNS -b 0.0.0.0 -l 5353 -L 8.8.8.8:53 -U
	
	/usr/sbin/ipset -N gfwlist iphash

	## for tcp redir
	/usr/sbin/iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1081
	/usr/sbin/iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1081
	
	## for udp redir
	/usr/sbin/ip route add local default dev lo table 100
	/usr/sbin/ip rule add fwmark 1 lookup 100
	/usr/sbin/iptables -t mangle -A PREROUTING  -p udp -m set --match-set gfwlist dst -j TPROXY --on-port 1082 --tproxy-mark 0x01/0x01

	## add all ip.txt to ipset 
	while read -r line 
	do
		/usr/sbin/ipset -A gfwlist $line
	done < $CONFIG_IPFILE
	

	if [ ! -d /tmp/dnsmasq.d ]
	then
		mkdir -p /tmp/dnsmasq.d
		sed -i '/conf-dir=\/tmp\/dnsmasq.d/d' /etc/dnsmasq.conf
		echo "conf-dir=/tmp/dnsmasq.d" >> /etc/dnsmasq.conf
	fi
	
	cp -f $CONFIG_GFWLIST /tmp/dnsmasq.d
	cp -f $CONFIG_CUSLIST /tmp/dnsmasq.d
	
	/etc/init.d/dnsmasq stop
	/etc/init.d/dnsmasq start

	## add watch dog job
	LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
	echo '['$LOGTIME'] Start Watchdog ' >> /var/log/shadowsocks_watchdog.log

	/usr/bin/crontab -l | { cat; echo "*/10 * * * * /etc/shadowsocks/ss-watchdog >> /var/log/shadowsocks_watchdog.log 2>&1"; echo "0 1 * * 0 echo \"\" > /var/log/shadowsocks_watchdog.log"; } | /usr/bin/crontab -

}

stop() {

	## remove watch dog job
	/usr/bin/crontab -l | { /bin/sed '/shadowsocks_watchdog.log/d'; } | /usr/bin/crontab -

	LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
        echo '['$LOGTIME'] Stop Watchdog ' >> /var/log/shadowsocks_watchdog.log

	/usr/sbin/ip route del local default dev lo table 100
	/usr/sbin/ip rule del fwmark 1 lookup 100
	/usr/sbin/iptables -t mangle -D PREROUTING  -p udp -m set --match-set gfwlist dst -j TPROXY --on-port 1082 --tproxy-mark 0x01/0x01	
	
	/usr/sbin/iptables -t nat -D PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1081
	/usr/sbin/iptables -t nat -D OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1081
	/usr/sbin/ipset -X gfwlist 

	service_stop /usr/bin/ss-redir-tcp
	sleep 1
	service_stop /usr/bin/ss-redir-udp
	sleep 1
	service_stop /usr/bin/ss-tunnel
	
	rm -f /tmp/dnsmasq.d/shadow*  
	
	/etc/init.d/dnsmasq stop
	/etc/init.d/dnsmasq start
	
	rmdir $LOCK_FILE
}

restart(){
        stop
        start
}

